# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "S03-WF2: Test Project"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: Install Dependencies
        working-directory: ./section-02
        run: npm ci
      - name: Run Tests
        working-directory: ./section-02
        run: npm test
