# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "S03-WF2: Deploy Project"

on: push

defaults:
  run:
    working-directory: ./section-02

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: Install Dependencies
        # working-directory: ./section-02
        run: npm ci
      - name: Run Tests
        # working-directory: ./section-02
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: Install Dependencies
        # working-directory: ./section-02
        run: npm ci
      - name: Run Build
        # working-directory: ./section-02
        run: npm run build
      - name: Deploy
        # working-directory: ./section-02
        run: echo Deploying...
